#!/bin/sh

COMMIT=$(git log -n1 --pretty='%h')
VERSION=$(git describe --exact-match --tags $COMMIT)

if test $? -ne 0; then
    VERSION=v$(date +%Y%j)-$COMMIT
fi

tee version-number.go >/dev/null <<EOF
// Code generated by go generate; DO NOT EDIT.
package main

var versionNumber string = "$VERSION"
EOF
